language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  app: national-parkfinder
  skip_cleanup: true
  api_key:
    secure: B77XJEwncNxpJYHvdL9xGSgnsmmaxZXS30Fc9BFRUOr2yF2BIZ+lURgDp8wU5zAR1SSfdFHAdeNbOq7U32emY40doyfDfA3EhNV8EtlfNQhZqtZ4ZDwX1FsYK01Gv5/wonhKNdEDz5WT/JVh4weN6S9ZIfbWu0Yo1CMgxr4dPKHBtU3IOyFzRTYCC7hEeGehPkrz+1nSoh85egNpLYfxfHa/p1ggkgzEiiCpepr+AlhfBxrQQtM+TCdmTrGZMp5U15x1OvQZU1p3X30P4Y9RNFb8gtVZTW5ocI5JPKJAwJ+m/gTqb222cOutkjk92M15BB/BENK6Gb4hjtPndTqqCWndZEq8fx71BtJtMQLmj2H5OK6ZQwpcRDBV1L4j1H+VTd8sM0uxiZYsVu3EM8MfcmRYvXBSZdxZROojx2pFbI/MfEhrFvYiyZee5rJeXa7gU1KURH1n7aVgH5TyJGNwhVy6cKRAj+Ledz7bXfUfq5QYGhqeJ3V2YvKv3dLA6SM5UM92IqJGBECw563KW5GMXBIjtUDvATuwOeS9q3igNbYaNYIZv4flZx8V/2z4L26VBxhYGOwMg8Fauv9y8DC92dkzgfBD7yyy3EioCll+q1Z2GpzvjRRQ3sap8aVt1KNxhyDyvSxYIsfbpaP+LQvyMS3vJhEg0DONVDdDL7DZ3qg=
  on: main
